version: "3.8"
services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "18000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
  dynamo-admin:
    image: "aaronshaf/dynamodb-admin:latest"
    ports:
      - "18001:8001"
    environment:
      DYNAMO_ENDPOINT: dynamodb-local:8000
    depends_on:
      - "dynamodb-local"
